/* ══════════════════════════════════════════════════════
   PHOTO CONFIGURATION
   ─────────────────────────────────────────────────────
   TO ADD A PHOTO: put the file in the photography/ folder.
   That is the whole job. This list builds itself.

   NAMING CONVENTION — name every file like this:
     YYYYMMDD_Your caption text.jpg
     e.g.  20260219_Staircase at MBS in Singapore.jpg

   Spaces, commas, and accents are all fine. The date and
   caption shown on the site are read from the filename, so
   the filename IS the content. Get it right at export time.

   A file whose name does not start with 8 digits will still
   appear, but with a nonsense caption. That is deliberate:
   a visible mistake gets fixed, a hidden one does not.

   ORDER: sorted newest to oldest in the browser. The order
   Jekyll writes below does not matter.

   TWO SIZES: the grid loads a 600px WebP thumbnail generated at
   build time by tools/build-thumbnails.py. The lightbox loads
   your full-resolution original. Thumbnails are never committed;
   they are created fresh each time the site is built.
══════════════════════════════════════════════════════ */

// The list below is generated by Jekyll from the photography/ folder.
// Do not edit it by hand. Add a photo by adding a file.
const PHOTOS = [
{%- assign gallery = site.static_files | where_exp: "f", "f.path contains '/photography/'" -%}
{%- for f in gallery -%}
{%- if f.extname == '.jpg' or f.extname == '.jpeg' or f.extname == '.JPG' or f.extname == '.JPEG' or f.extname == '.png' %}
  { src: "{{ f.path }}", thumb: "/photography/thumb/{{ f.basename }}.webp" },
{%- endif -%}
{%- endfor %}
];

const MONTHS = ['January','February','March','April','May','June',
                'July','August','September','October','November','December'];

function parsePhotoFilename(src) {
  // Decode any URL-encoded characters (e.g. %20 → space)
  const decoded = decodeURIComponent(src);
  const full = decoded.split('/').pop().replace(/\.[^.]+$/, '');
  const match = full.match(/^(\d{4})(\d{2})(\d{2})_(.+)$/);
  if (match) {
    const year    = parseInt(match[1], 10);
    const month   = parseInt(match[2], 10);
    const day     = parseInt(match[3], 10);
    const caption = match[4].trim();
    const dateStr = day + ' ' + (MONTHS[month - 1] || '') + ' ' + year;
    return { caption, date: dateStr };
  }
  return { caption: full, date: '' };
}

/* ══ PHOTO GRID ══ */
(function initPhotos() {
  const grid = document.getElementById('photoGrid');
  if (!PHOTOS.length) return;

  const sorted = [...PHOTOS].sort((a, b) => {
    const fn = s => decodeURIComponent(s).split('/').pop();
    const dateA = (fn(a.src).match(/^(\d{8})/) || ['0'])[0];
    const dateB = (fn(b.src).match(/^(\d{8})/) || ['0'])[0];
    return dateB.localeCompare(dateA);
  });

  sorted.forEach((photo, idx) => {
    const item = document.createElement('div');
    item.className = 'photo-item';
    item.dataset.idx = idx;
    const { caption } = parsePhotoFilename(photo.src);
    const img = document.createElement('img');
    img.src = photo.thumb || photo.src;   // thumbnail in the grid, falls back to the original
    img.alt = caption;
    img.loading = 'lazy';
    item.appendChild(img);
    item.addEventListener('click', () => openLightbox(idx));
    grid.appendChild(item);
  });

  PHOTOS.length = 0;
  sorted.forEach(p => PHOTOS.push(p));

  const obs = new IntersectionObserver(entries => {
    entries.forEach(entry => {
      if (entry.isIntersecting) {
        const i = parseInt(entry.target.dataset.idx || 0);
        setTimeout(() => entry.target.classList.add('visible'), i * 35);
        obs.unobserve(entry.target);
      }
    });
  }, { threshold: 0.04 });
  document.querySelectorAll('.photo-item').forEach(el => obs.observe(el));
})();

/* ══ LIGHTBOX ══ */
let lbIndex = 0;

function alignMeta() {
  requestAnimationFrame(() => {
    const img    = document.getElementById('lightboxImg');
    const footer = document.querySelector('.lightbox-footer');
    const meta   = document.getElementById('lightboxMeta');
    const imgRect    = img.getBoundingClientRect();
    const footerRect = footer.getBoundingClientRect();
    // Set left padding of footer to match image left edge
    const leftOffset = Math.max(16, imgRect.left - footerRect.left);
    footer.style.paddingLeft = leftOffset + 'px';
    // Set meta width to match image width so counter aligns with right edge
    meta.style.width = imgRect.width + 'px';
  });
}

function openLightbox(idx) {
  if (!PHOTOS.length) return;
  lbIndex = idx;
  updateLightbox();
  document.getElementById('lightbox').classList.add('open');
  document.body.style.overflow = 'hidden';
  // align after lightbox is visible and image has rendered
  const img = document.getElementById('lightboxImg');
  if (img.complete) alignMeta();
}
function closeLightbox() {
  document.getElementById('lightbox').classList.remove('open');
  document.body.style.overflow = '';
}
function lightboxNav(dir) {
  lbIndex = (lbIndex + dir + PHOTOS.length) % PHOTOS.length;
  updateLightbox();
}
function updateLightbox() {
  const p = PHOTOS[lbIndex];
  const { caption, date } = parsePhotoFilename(p.src);
  const img = document.getElementById('lightboxImg');
  img.src = p.src;
  img.alt = caption;
  document.getElementById('lightboxCounter').textContent = (lbIndex + 1) + ' / ' + PHOTOS.length;
  document.getElementById('lightboxCaption').textContent = caption;
  document.getElementById('lightboxDate').textContent    = date;
  // Re-align once image has loaded (handles portrait vs landscape)
  img.onload = alignMeta;
  if (img.complete) alignMeta();
}

// Re-align on window resize
window.addEventListener('resize', () => {
  if (document.getElementById('lightbox').classList.contains('open')) alignMeta();
});

document.addEventListener('keydown', e => {
  const lb = document.getElementById('lightbox');
  if (!lb.classList.contains('open')) return;
  if (e.key === 'ArrowLeft')  lightboxNav(-1);
  if (e.key === 'ArrowRight') lightboxNav(1);
  if (e.key === 'Escape')     closeLightbox();
});
document.getElementById('lightbox').addEventListener('click', e => {
  if (e.target.id === 'lightbox') closeLightbox();
});
// Click on the stage (white space next to photo) also closes lightbox
document.getElementById('lightboxStage').addEventListener('click', e => {
  if (e.target.id === 'lightboxStage') closeLightbox();
});

// Mobile swipe support
(function() {
  const lb = document.getElementById('lightbox');
  let touchStartX = 0;
  let touchStartY = 0;
  lb.addEventListener('touchstart', e => {
    touchStartX = e.touches[0].clientX;
    touchStartY = e.touches[0].clientY;
  }, { passive: true });
  lb.addEventListener('touchend', e => {
    const dx = e.changedTouches[0].clientX - touchStartX;
    const dy = e.changedTouches[0].clientY - touchStartY;
    if (Math.abs(dx) > Math.abs(dy) && Math.abs(dx) > 40) {
      lightboxNav(dx < 0 ? 1 : -1);
    }
  }, { passive: true });
})();
